### ISSUE TITLE
Reporte de diagrama de clase y secuencia 

### ISSUE THREAD

**Issue by SandyMarissaGs** [SistemasTecTlaxiaco/actividad-9-diagrama-de-clases-secuencia-equipo-s-b-j#2]
[REPORTE_DE_PRACTICA_SOBRE_LOS_DIAGRAMAS DE CLASE Y DE SECUENCIA.pdf](https://github.com/user-attachments/files/18042979/REPORTE_DE_PRACTICA_SOBRE_LOS_DIAGRAMAS.DE.CLASE.Y.DE.SECUENCIA.pdf)

Diagramas en la wiki:
https://github.com/SistemasTecTlaxiaco/CryptoStream/wiki/5.4-Diagrama-de--Clases
https://github.com/SistemasTecTlaxiaco/CryptoStream/wiki/5.5-diagrama-de-secuencia

**Comment by Anakimberly** [comment]
Obtuvieron 29% de 30% de acuerdo a la rubrica

**Comment by josealfredo79** [comment]
Bien hecho y revisado...
